---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/annekerr/public_html/
    - /bin/cp -Rf /home4/annekerr/repositories/Photography-Web-Site/css $DEPLOYPATH
    - /bin/cp -Rf /home4/annekerr/repositories/Photography-Web-Site/images $DEPLOYPATH
    - /bin/cp -f /home4/annekerr/repositories/Photography-Web-Site/*.html $DEPLOYPATH
    - /bin/cp -Rf /home4/annekerr/repositories/Photography-Web-Site/essay $DEPLOYPATH
